media:
  input: public/images
  output: /images

content:
  - name: homepage
    label: Homepage Content
    type: file
    path: content/site.json
    fields:
      - label: Logo Image URL
        name: logo_url
        type: string
      - label: Headshot Image URL
        name: headshot_url
        type: string
      - label: Lead Image URL
        name: lead_image_url
        type: string
      - label: Hero Title
        name: hero_title
        type: string
      - label: Hero Body
        name: hero_body
        type: text
      - label: Philosophy Header
        name: philosophy_header
        type: text
      - label: Philosophy Quote
        name: philosophy_quote
        type: text
      - label: Services Header
        name: services_header
        type: string
      - label: Services
        name: services
        type: object
        list: true
        fields:
          - label: Service Title
            name: title
            type: string
          - label: Service Description
            name: description
            type: text
      - label: About Header
        name: about_header
        type: string
      - label: About Text
        name: about_text
        type: text
      - label: FAQs
        name: faqs
        type: object
        list: true
        fields:
          - label: Question
            name: question
            type: string
          - label: Answer
            name: answer
            type: text
  - name: insights
    label: Insights
    type: collection
    path: _posts
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean        
      - name: body
        label: Main Text
        type: rich-text